#!/bin/bash
#SBATCH -p interactive
#SBATCH --qos nopreemption
#SBATCH --gres=gpu:1
#SBATCH -c 4
#SBATCH --mem=32GB
#SBATCH --job-name=test_jupyter
#SBATCH --output=notebook_output-%j.log

echo Running on $(hostname)

# activate environment
module load python/3.9.10

# choose a random port
cd ~/Projects/Legendre
poetry run jupyter-lab --ip 0.0.0.0 --port 2255