#!/bin/bash
#SBATCH --job-name=cnode

#SBATCH --partition=p100,t4v1,t4v2,rtx6000

#SBATCH --gres=gpu:1

#SBATCH --qos=normal

#SBATCH --cpus-per-task=4

#SBATCH --mem-per-cpu=8G

#SBATCH --output=slurm-%j.out

#SBATCH --error=slurm-%j.err

# prepare your environment here
module load python/3.9.10

# put your command here
cd ~/Projects/Legendre/legendre/train_scripts/

poetry run python train_node.py --model_type=CNODE --corr_time=0.2 --irregular_rate=0.8 --N=2000