#!/bin/bash
#SBATCH --job-name=cnode

#SBATCH --partition=p100,t4v1,t4v2,rtx6000

#SBATCH --gres=gpu:1

#SBATCH --qos=normal

#SBATCH --mem=4G

#SBATCH -c 4

#SBATCH --output=outputs/slurm-%j.out

#SBATCH --error=outputs/slurm-%j.err

# prepare your environment here
module load python/3.9.10

# put your command here
cd ~/Projects/Legendre/legendre/train_scripts/

poetry run wandb agent edebrouwer/orthopoly/c6yoaram